# fly.toml app configuration file generated for fso-part3-1 on 2024-02-13T16:25:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fso-part3-1'
primary_region = 'arn'


[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
